export const LOAD_TODO_REQUEST = 'LOAD_TODO_REQUEST'
export const LOAD_TODO_SUCCESS = 'LOAD_TODO_SUCCESS'

export const ADD_TODO_REQUEST = 'ADD_TODO_REQUEST'
export const ADD_TODO_SUCCESS = 'ADD_TODO_SUCCESS'

export const DELETE_TODO_REQUEST = 'DELETE_TODO_REQUEST'
export const DELETE_TODO_SUCCESS = 'DELETE_TODO_SUCCESS'

export const DELETE_ALL_TODOS_REQUEST = 'DELETE_ALL_TODOS_REQUEST'
export const DELETE_ALL_TODOS_SUCCESS = 'DELETE_ALL_TODOS_SUCCESS'

export const UPDATE_TODO_REQUEST = 'UPDATE_TODO_REQUEST'
export const UPDATE_TODO_SUCCESS = 'UPDATE_TODO_SUCCESS'

export const UPDATE_FILTER = 'UPDATE_FILTER'
