export const ADD_TODO = 'ADD_TODO';
export const DELETE_TODO = 'DELETE_TODO';
export const DELETE_ALL_TODOS = 'DELETE_ALL_TODOS';
export const DELETE_INFO_BAR_ELEM = 'DELETE_ALL_TODOS';
export const TOGGLE_TODO_STATUS = 'TOGGLE_TODO_STATUS';
export const STATE_UPDATED = 'STATE_UPDATED';
