export const ADD_TODO_REQUEST = 'ADD_TODO_REQUEST'
export const ADD_TODO_SUCCESS = 'ADD_TODO_SUCCESS'

export const DELETE_TODO_REQUEST = 'DELETE_TODO_REQUEST'
export const DELETE_TODO_SUCCESS = 'DELETE_TODO_SUCCESS'

export const DELETE_ALL_TODOS_REQUEST = 'DELETE_ALL_TODOS_REQUEST'
export const DELETE_ALL_TODOS_SUCCESS = 'DELETE_ALL_TODOS_SUCCESS'

export const TOGGLE_TODO_STATUS = 'TOGGLE_TODO_STATUS'
export const CHANGE_TODO = 'CHANGE_TODO'
export const STATE_UPDATED = 'STATE_UPDATED'
